# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2fd4382545d20d3304674bd9ff861e310d1fac52154f02d2af5a884d47adf52b38392a3c2a40d078305deeed14cb81e29c6c7b84b906112920bdc42fb3fd286

test:
  secret_key_base: 2b6362e9b3f6565ce62f11de00f401aa194368e2722c983784e14a536296c3bef1d4a6289b170cef5304868706fd0d379b1b0f58444538591a22638e32f945f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
